### ISSUE TITLE
Hacktoberfest 2019: Adobe

### ISSUE THREAD

**Issue by Akashd7** [swapagarwal/swag-for-dev#372] opened 2019-10-04 18:03 UTC
## Wild swag opportunity appeared!

- [✔ ] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Adobe

Q. Where have you seen the announcement (URL)?  
A. :https://community.magento.com/t5/Magento-DevBlog/Squashtoberfest-2019/ba-p/143694

Q. What kind of swag (clothing, stickers, ...)?  
A. : Stickers & T-Shirt

Q. Have you received swag from this?  
A. : Yes

Q. Does it ship worldwide?  
A. : Yes

- [ ✔] I've checked that the promotion is legit.
- [ ✔] I've checked that it's still available to the public.

**Comment by Akashd7** [comment] 2019-10-04 18:03
Create five PRs on either Adobe or Magento repositories during the month of October. Adobe team will file an issue in November in this repo listing out qualifiying contributors’ handles in the file with further instructions to get the swags.

**Comment by vikaspotluri123** [comment] 2019-10-04 20:02
Closing as a duplicate of #360 😄

**Closed by vikaspotluri123** 2019-10-04 20:02 UTC
