### ISSUE TITLE
We dont have enough women's swag. 

### ISSUE THREAD

**Issue by jayzalowitz** [swapagarwal/swag-for-dev#1] opened 2018-02-18 19:22 UTC
This is more of a comment to remind people submitting pull requests that they should totally consider buying women's sizes when doing swag. 

Also, get creative.

**Comment by alexknuckles** [comment] 2018-02-18 19:43
The socks, hoodies, t-shirts, and stickers in this list are unisex. Don't create problems where they don't exist to pat yourself on the back.

**Comment by manojlds** [comment] 2018-02-18 19:47
As far as I can remember, Hacktoberfest asks for men/women sizes. And others seem to be unisex. Like @alexknuckles says, just trying to pat yourself on the back?

**Comment by jayzalowitz** [comment] 2018-04-26 05:33
@alexknuckles, didn't realize that was the case, my bad. Just have a lot of friends who have a very big issue with them never getting swag so was trying to help. Perhaps clearly label as unisex?

**Comment by alexknuckles** [comment] 2018-04-26 06:18
Lots of friends with an issue of not getting swag? Based on the issue you opened, it was caused by unnecessarily gendered products, right? Can you provide some specific examples of your friends receiving swag that wasn't for their gender? If that has actually happened, maybe the companies giving the free products away are the best place to raise the issue. 

This project's only aim is to compile free swag opportunities for developers. It has no mention of gender, so you are only adding to the problem of social exclusion by opening this issue here.

**Comment by alexknuckles** [comment] 2018-04-26 06:37
This project's only aim is to compile free swag opportunities for developers. It has no mention of gender. If you have an issue with the free products offered, your best bet would be to raise an issue with the companies giving away what you see as gendered products.

**Comment by bigwoodenspoon** [comment] 2018-04-26 22:06
Unisex T-shirts are basically "shirts that fit guys and so we also give them to girls."  It's literally the exact same pattern.

I don't know if this is a specific event we are referring to, but broadly speaking, this is a problem.

**Comment by kevin51jiang** [comment] 2018-04-26 23:07
Can we close this thread? I feel like it's going to become a political argument very soon.

**Closed** 2018-09-20 06:18 UTC
Labels: invalid
