### ISSUE TITLE
Add "done with this swag" checkbox to each swag

### ISSUE THREAD

**Issue by shakeabi** [swapagarwal/swag-for-dev#439] opened 2019-10-16 02:53 UTC
## Issue regarding the website

- [x] I've checked that this isn't a duplicate issue.

Add "done with this swag" checkbox ( and store the data in the localstorage ) to each swag so that we can see which swags we've completed. This is particularly useful during hacktoberfest.

**Comment by vikaspotluri123** [comment] 2019-10-16 02:55
Duplicate of #151 😉

**Closed by vikaspotluri123** 2019-10-16 02:55 UTC

**Comment by shakeabi** [comment] 2019-10-16 03:04
sry :'(
