### ISSUE TITLE
Add Ballerina swags opportunity

### ISSUE THREAD

**Issue by aashishpanthi** [swapagarwal/swag-for-dev#1140] opened 2023-10-19 15:41 UTC
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Ballerina

Q. Where have you seen the announcement (URL)?  
A. : Here: https://ballerina.io/hacktoberfest/

Q. What kind of swag (clothing, stickers, ...)?  
A. : 25$ Amazon Voucher, Sticker Pack, T-shirt

Q. Have you received swag from this?  
A. : No

Q. Does it ship worldwide?  
A. : Yes

Any accepted PR fixing a Hacktoberfest Issue will receive 25$ Amazon Voucher, Sticker Pack, T-shirt

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by aslafy-z** [comment] 2023-10-19 19:28
This is a duplicate of https://github.com/swapagarwal/swag-for-dev/issues/1140
You checked the `I've checked that this isn't a duplicate issue.` without checking if there was an issue. This is even already on the website! Please stop opening duplicate/invalid swag, I have enough triage work to do...

**Closed** 2023-10-19 19:29 UTC
