### ISSUE TITLE
Create Google code-in swag oppertunity

### ISSUE THREAD

**Issue by vmr1532** [swapagarwal/swag-for-dev#270] opened 2019-04-14 04:24 UTC
## Wild swag opportunity appeared!

- [ ] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : GOOGLE CODE IN

Q. Where have you seen the announcement (URL)?  
A. : https://codein.withgoogle.com/archive/

Q. What kind of swag (clothing, stickers, ...)?  
A. : TSHIRT,STICKERS

Q. Have you received swag from this?  
A. : NO

Q. How long did it take?  
A. : 1 MONTH

Q. Does it ship worldwide?  
A. : 

- [ ] I've checked that the promotion is legit.
- [ ] I've checked that it's still available to the public.

**Comment by Yash-Garg** [comment] 2019-04-14 04:28
2019 one has not started yet, why creating an issue now?

**Comment by vmr1532** [comment] 2019-04-14 04:29
just created this for reference for letting others know such opportunity exists

**Comment by Yash-Garg** [comment] 2019-04-14 08:35
Oh okay, great then !

**Comment by sidhyatikku** [comment] 2019-05-09 10:31
@vmr1532 this seems misleading. Imo you should've created a post after 2019 GCI started.

**Comment by aslafy-z** [comment] 2019-05-27 17:14
Closing this as it's a duplicate of #175 

Thanks anyway @vmr1532

**Closed by aslafy-z** 2019-05-27 17:14 UTC
