### ISSUE TITLE
Add Light/Dark Mode Toggle to the Page

### ISSUE THREAD

**Issue by Tejas-Sharma-dev** [swapagarwal/swag-for-dev#1264] opened 2024-09-30 05:23 UTC
- [x] I've checked that this isn't a duplicate issue.

I suggest adding a toggle switch for light and dark modes on the page. This feature will enhance user experience by allowing them to switch between light and dark themes based on their preferences, especially in different lighting environments.

**Comment by aslafy-z** [comment] 2024-09-30 07:26
Hey,
This issue is a duplicate of https://github.com/swapagarwal/swag-for-dev/issues/106.
Please follow there

**Closed by aslafy-z** 2024-09-30 07:26 UTC

**Comment by Tejas-Sharma-dev** [comment] 2024-09-30 08:24
Oops, I did not check, my bad, will note this before opening issue
