### ISSUE TITLE
Add opsdroid swag

### ISSUE THREAD

**Issue by Yash-Garg** [swapagarwal/swag-for-dev#219] opened 2018-12-11 12:56 UTC
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : OpsDroid

Q. Where have you seen the announcement (URL)?  
A. : On their Github repository

Q. What kind of swag (clothing, stickers, ...)?  
A. : Stickers

Q. Have you received swag from this?  
A. : Yes, I will receive it soon

Q. Does it ship worldwide?  
A. : Yes

- You need to be a contributor on their github repository -> https://github.com/opsdroid

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by aslafy-z** [comment] 2018-12-11 12:58
Duplicate of #216, please report in the existing issue.

**Comment by Yash-Garg** [comment] 2018-12-11 12:59
Ah, okay!

**Closed by aslafy-z** 2018-12-11 12:58 UTC
