### ISSUE TITLE
Add collectivai swag opportunity

### ISSUE THREAD

**Issue by aashishpanthi** [swapagarwal/swag-for-dev#1103] opened 2023-10-17 02:27 UTC
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : collectivai

Q. Where have you seen the announcement (URL)?  
A. : Here: https://collectivai.com/blog/hactoberfest-2023-t-shirts-are-not-entirely-gone

Q. What kind of swag (clothing, stickers, ...)?  
A. : Clothing

Q. Have you received swag from this?  
A. : No

Q. Does it ship worldwide?  
A. : Yes

Make four meaningful (read non-spam) contributions to any repo with >100 stars and fill out [this really simple form](https://tally.so/r/3xDxgJ). They will verify and ship a really cool merch kit anywhere you are in the world!

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by aslafy-z** [comment] 2023-10-17 06:59
Please take some time to look at the website and the issues to check if it is already on the list. Duplicate of #1090

**Closed by aslafy-z** 2023-10-17 06:59 UTC
