### ISSUE TITLE
Alexa New Swag Opportunity

### ISSUE THREAD

**Issue by Prabhman** [swapagarwal/swag-for-dev#396] opened 2019-10-06 20:12 UTC
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Amazon Alexa Developers

Q. Where have you seen the announcement (URL)?  
A. : https://developer.amazon.com/en-IN/alexa/alexa-skills-kit/alexa-developer-skill-promotion

Q. What kind of swag (clothing, stickers, ...)?  
A. : Clothing

Q. Have you received swag from this?  
A. : no

Q. How long did it take?  
A. : Dont know

Q. Does it ship worldwide?  
A. : India, US, UK, Germany, Japan, France, Italy, Spain, and Australia

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by aslafy-z** [comment] 2020-05-03 02:30
Duplicate of #166

**Closed by aslafy-z** 2020-05-03 02:30 UTC
Labels: :tada: new swag, good first issue, 🏃‍♂️ in progress
