### ISSUE TITLE
Digitalocean survey to get stickers 

### ISSUE THREAD

**Issue by krishnakakade1999** [swapagarwal/swag-for-dev#324] opened 2019-09-30 02:15 UTC
## Wild swag opportunity appeared!

- [ ] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : digitalocean 

Q. Where have you seen the announcement (URL)?  
A. : https://digitalocean.getfeedback.com/r/p44ADlqG/

Q. What kind of swag (clothing, stickers, ...)?  
A. : stickers smmay shark sticker

Q. Have you received swag from this?  
A. : i applied today 

Q. How long did it take?  
A. : hopefully 2 or 3 weeks 

Q. Does it ship worldwide?  
A. : yes 

- [ ] I've checked that the promotion is legit.
- [ ] I've checked that it's still available to the public.

**Comment by vikaspotluri123** [comment] 2019-09-30 02:17
Closing as a duplicate of #304 😄 Thanks!

**Closed** 2019-09-30 02:17 UTC
