### ISSUE TITLE
Add swag opportunity for Dyrectorio

### ISSUE THREAD

**Issue by dalvishruti14** [swapagarwal/swag-for-dev#1203] opened 2023-10-23 14:44 UTC
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Dyrectorio

Q. Where have you seen the announcement (URL)?  
A. : https://github.com/dyrector-io/dyrectorio/issues/837

Q. What kind of swag (clothing, stickers, ...)?  
A. :  Swag pack (may include stickers)

Q. Have you received swag from this?  
A. : No

Q. How long did it take?  
A. :  N/A

Q. Does it ship worldwide?  
A. : No (Only in Europe)

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by aslafy-z** [comment] 2023-10-23 19:19
Thank you @dalvishruti14 but this is a duplicate of https://github.com/swapagarwal/swag-for-dev/issues/1120 witch is already worked on at https://github.com/swapagarwal/swag-for-dev/pull/1207

**Closed** 2023-10-23 19:19 UTC
