### ISSUE TITLE
Hacktober

### ISSUE THREAD

**Issue by parisha99** [swapagarwal/swag-for-dev#685] opened 2020-09-30 17:51 UTC
## Wild swag opportunity appeared!

- [ ] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Hacktober

Q. Where have you seen the announcement (URL)?  
A. : 

Q. What kind of swag (clothing, stickers, ...)?  
A. : clothing

Q. Have you received swag from this?  
A. : no

Q. How long did it take?  
A. : few days

Q. Does it ship worldwide?  
A. : yes

- [ ] I've checked that the promotion is legit.
- [ ] I've checked that it's still available to the public.

**Comment by parisha99** [comment] 2020-09-30 17:52
This event is  from October 1 - October 31.

**Comment by vikaspotluri123** [comment] 2020-09-30 20:11
@parisha99 can you please share a link with more information. If you're referring to [hacktoberfest](https://hacktoberfest.digitalocean.com), that's already on the site :smile:

**Comment by parisha99** [comment] 2020-10-01 04:46
Hacktoberfest is going on from October 1- October 31. The link to the same- (https://www.google.com/url?sa=t&source=web&rct=j&url=https://hacktoberfest.digitalocean.com/&ved=2ahUKEwiPz5vJypLsAhUBOisKHZ5vDtMQFjACegQIChAB&usg=AOvVaw3WClc5XFd06zQEPs6Cb6dg) . In this challenge one have to complete 4 pull request to get a swag(T-shirt).

**Comment by vikaspotluri123** [comment] 2020-10-01 04:47
Closing as a duplicate of #665 🙂

**Closed** 2020-10-01 11:13 UTC
